name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [26.x, 24.x]

    steps:
    - uses: actions/checkout@v7

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v7
      with:
        node-version: ${{ matrix.node-version }}
        cache: yarn

    - name: Install dependencies
      run: yarn --frozen-lockfile

    - name: Type check
      run: yarn type-check

    - name: Build
      run: yarn build

    - name: Create package
      run: ./build-upload.sh

    - uses: actions/upload-artifact@v7
      with:
        name: artifact-chrome-${{ matrix.node-version }}-${{ github.sha }}
        path: ./dist/chrome/

    - uses: actions/upload-artifact@v7
      with:
        name: artifact-firefox-${{ matrix.node-version }}-${{ github.sha }}
        path: ./dist/firefox/

    - uses: actions/upload-artifact@v7
      with:
        name: artifact-edge-${{ matrix.node-version }}-${{ github.sha }}
        path: ./dist/edge/
